language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: monferrand
  password:
    secure: QURopstiPo12gFic8m5b05jLqxJodc+yV8aT3t2W/R3bdC+yOgyouMFpgB6yLV98Y6V14w1oW3x76W8GabadZPQQwZRkmaup4xiFEeiB/hKD7IqikCEvfrDFFE+JK/govX5AaauylTpwGRFrfVDGfsz3T4lrTFj3Y6Yk7iBkTGLAmW6fMEPAzX14bFU3RU8fOXVirE/E3uNSaULF6muwMogA0Mt1eDxgKZbVBUmmrzK022gUUsxOz4xzyMMCOCuwmDgnsMgRb96SYULzOp4zxMi87lq79J05v+Z96BORE0XqRSVjsjFZm3UVm2fJO6bMjfoNYaIQtVDaAQ7edBBR7Q/wmclv78YLeacfIzSGEoARUlmGR6XYfK92sMszjsD1+7ryGcJLtMAAk9Mz7TysAGgHDgPGZqNNtJ8rrYor5b/aZpsgkZ/NfoHmyfqZ/9e9Q6eObxQ7Xtaur6jbHAhl9zpTOiuc7dSSMUxm0JJO2Icy/YDoFAgaa5xQU3F6OUJ4zerB1PmCWzRnyOBPycXXYUcUovSo5Six6AbMMJvaAOeuJDR0NUsb1m8DZAhzfhdXm27+b/5R3bCLjplwYgiD7piNeSwqF++zAEzM96LDPIdIwALQz/fTaW1ktHaz3NTYiywZNqflnYXFZMBKlGpjzB3yPhR4msyeoMts2hUdZs8=
  on:
    tags: true
    repo: monferrand/medstat
    python: 3.8
